### ISSUE TITLE
Serialize MapName (and other MapInfo?) and move mapname to EntityData

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#302]
### aka, MapName shows `City_00_01` instead of `Atlas Park`
Feel free to provide feedback or input on direction for this Enhancement.

### Summary
Unless the Client has map display names hardcoded, there must be a way for us to pull that map name out for use throughout the server (e.g. FriendsList, TeamsList, Char Select, etc)

There may also be other info that we'll want to store in some kind of new MapStruct for use as MapInstance begins to recognize multiple zones.

Additionally, currently `m_mapname` is stored in `CharacterData` under Character. In reality, we should move this to `EntityData` inside Entity, as every Entity should know what map it's in (besides every Character is an Entity). It's possible that we'll want to rename this to `m_current_map` or something instead.

There are some comments in `map_serializers.cpp` that may provide insight into what's stored in maps.bin
```
//static Serialization_Template Map_Tokens[6] = {
//{ "Name", TOKEN_STRING, 0x10},
//{ "Icon",  TOKEN_STRING, 0x14},
//{ "Location",  TOKEN_VEC2, 0},
//{ "TextLocation",  TOKEN_VEC2, 8},
//{ "End",  TOKEN_END},
//{ },
//};

//static const Serialization_Template Map_Token[2] = {
//{ "Zone", TOKEN_SUB_TABLE, 0, 0x18, Map_Tokens},
//{},
//};
```
### Tasks to complete this issue:
- [ ] Research what is stored client side related to map data/info (maps.bin, maybe others)
- [ ] Serialize relevant map data in map_serializers.cpp using Cereal
- [ ] Rename `m_mapname` to `m_current_map`
- [ ] Move `m_current_map` to `EntityData` struct

**Comment by nemerle** [comment]
We could extract map names using map.bin, although the file itself contents are not exactly what we want/need since the atlas park entry looks like
```json
{
"Name" : "maps/City_Zones/City_01_01/City_01_01.txt",
"Icon" : "City_01_01_Atlas_Park.tga"
}
```
We 'can' extract the map name from the splash screen name, and build an dictionary for internal_map_name to user_visible_map_name.

Although we could consider creating our own simple format and loading it instead ?

**Comment by broxen** [comment]
Maybe easier just to create our own array then? Possible first use-case for Lua script? Allow users to rename their zones if they want.

```
-- Add this zone to the zones table
outbreak = {
  zone_id = 1,
  name = "City_00_01",
  displayname = "Outbreak",
  customspawn = {x = -61, y = -0, z = 161}, -- y is the elevation
}
zones.insert(outbreak, "outbreak")
```

If not LUA, maybe yaml or json for simple strings and settings?

**Comment by broxen** [comment]
Actually, just rereading your comment... if the naming schema is consistent, a good interim solution *would be* to pull this from the name:

`"Icon" : "City_01_01_Atlas_Park.tga"` and strip out **Atlas_Park** and remove the underscore, like what we do with NPC names.

**Comment by eos428** [comment]
I think I'll hop on this one, if you don't mind :) I think we can check based on city_00_01 and so on and get our map detail from there.

Some things I'd like to ask regarding this issue...
- Where do we give the map name in client's character select screen (eg MapInstance/city_00_01) to display from the server?
- Is struct Map_Data going to be stored in characters' db entries or just the map name?

**Comment by broxen** [comment]
To answer your question @eos428, no Map_Data should not be stored in the database. Just current map, either by name or by referenced ID

**Comment by eos428** [comment]
Ah, good to hear then. Then I'd assume we'd store the map datas in some files server-side?

Also, PR is ready for testing and looks fine on my end, have a look when you are free :)
