### ISSUE TITLE
Items Required for Proper Email System

### ISSUE THREAD

**Issue by PsiLupan** [Segs/Segs#327]
*  Add emails to the database upon EmailSend (This will likely require some input sanitizing)
Ex. /emailsend "\q[Name]\q " "Subject" "Content"

* Generate a timestamp on the sent email as the client does not send this information

 This is the number of seconds elapsed since Y2K relative to the server's defined timezone (Currently 0, -12 GMT), which can be done using 

This can be done using http://doc.qt.io/qt-5/qdatetime.html#secsTo like so:

`QDateTime y2k(QDate(2000, 1, 1), QTime(0, 0));`

`int timestamp = (int)y2k.secsTo(QDateTime::currentDateTime());`

* Use EmailMessageStatus event on Success/Failure of Send

This is used if a recipient does/doesn't exist. So, you would need to lookup the recipient name in the database.

* Remove emails from database with EmailDelete (Will need to check that the entity ID is the owner, as EmailDelete only sends "emaildelete [id]")

**Comment by broxen** [comment]
Per conversation on discord April 25th, 4:30pm PST between psiLupan and nemerle, and featuring others.

### Proposed `emails` in `segs_game`
Since all that is really stored is per-user "Inbox", we should simply add Serialized email data to PlayerData struct. That serialized EmailData should be a struct containing sender_id, recipient_id, subject, message body, and any other relevant data passed by the email system.

### Tasks for Completion
- [ ] Create EmailData struct
- [ ] Add necessary fields for email system to EmailData
- [ ] Leverage new EmailData struct throughout existing EmailMessageStatus
- [ ] Add EmailData to PlayerData struct
- [ ] Add Archive functions to PlayerData to properly serialize EmailData. Look to GUISettings for an example.

@PsiLupan or @nemerle feel free to chime in if I forgot anything here.

**Comment by broxen** [comment]
#367 relates to this as well

**Comment by broxen** [comment]
This portion of this was completed in v6
