### ISSUE TITLE
[Meta] How Can I Help? aka Future Server Features (and Opcodes to implement)

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#519]
## Summary
We need to implement these items one by one. I'm marking this `good-first-issue` as although these aren't all simple tasks, this can become a great resource for new members of all skill levels looking for how to help in meaningful ways.

When you take on one of the tasks (or groups) below, please [create a new issue](https://github.com/Segs/Segs/issues/new) to track your progress. Thank you!

See FloatingDamage for reference on how to implement server->client pkt communication: [Segs/Projects/CoX/Servers/MapServer/Events/FloatingDamage.h](https://github.com/Segs/Segs/blob/develop/Projects/CoX/Servers/MapServer/Events/FloatingDamage.h)

## Check the Issue Queue
- [Issues labeled `bug`](https://github.com/Segs/Segs/labels/bug)
- [Issues labeled `good first issue`](https://github.com/Segs/Segs/labels/good%20first%20issue)
- [Issues labeled `enhancement`](https://github.com/Segs/Segs/labels/enhancement)
- [Issues labeled `wishlist`](https://github.com/Segs/Segs/labels/wishlist)

### Low Difficulty
- Force Client Logout (boot client) -- useful for GM's to disconn. unruly guests
- Client Console Output -- print to client console
- Client Console PrintF -- printf to client console
- Correlate Map Indexes with Original Servers -- In Review: see #584
- Create "Current Features" list on Wiki -- see #554
- Replace `std::unique_ptr<T>(newT())` with `std::make_unique()` calls -- see #532 
- Normalize basic type arguments -- see #357 
- Update server architecture on wiki -- see #333 

### Moderate Difficulty
- Stores
- SuperGroup Registration *-- follow progress in #549* 
- Bug Report Window and researching a possible backend for linking this to github's issue tracker: #287 #35 
- Initiate Respec - using `/start_menu 13` somehow?
- Implement City Info Kiosk and Stats -- This is partially done (see: StandardDialogCmd, and implement `/kiosk home`). Will need to track Victors, Punishers, Healers, and Nemeses on a daily and monthly basis.
- Database schema migrations for updates to the database
- Map Cells Fog of War (packet 22) - Partially implemented #371
- Control Player (pkt 38)
- *Send Team-removal and Sidekick-removal messages -- see #555 and #642* 

### High Difficulty
- StatisticsService
- Proper per-map NPC Serialization #73 - Right now Outbreak spawns correctly, but AP, KR, etc do not. 
- Animations (aka Sequences)
- Particles and FX (aka NetFX)
- Fix Entity Movement #94
- Collision #81 

### Misc: 
- [ ] Force Client Logout (boot client) (packet 12)
- [ ] Client Console Output (packet 17)
- [ ] Client Console PrintF (packet 19)
- [ ] Map Cells Fog of War (packet 22) - Partially implemented #371 
- [ ] Control Player (pkt 38)
- [ ] Send VisitLocations (not sure of purpose, maybe early badges?) (pkt 63)
- [ ] Store Open (pkt 78)
- [ ] Store Close (pkt 79)
- [ ] Bug Report (pkt 80) -- Track in: #287 #35 

### Taskforces
- [ ] Taskforce Kick (packet 26)
- [ ] Taskforce Quit (packet 27)

### *Implement Supergroup Registration -- In Progress: #549*
- [x] Supergroup Offer (pkt 29)
- [x] Supergroup Create (pkt 30)
- [x] Supergroup Costume (pkt 31)
- [x] Register Supergroup (pkt 74)

### Mission Related
- [ ] Mission Entry Text (pkt 49)
- [ ] Mission Kick (pkt 50)
- [ ] Mission Objective Timer (pkt 73)

**Comment by broxen** [comment]
Updated with some other tasks, and reorganized.

**Comment by broxen** [comment]
Updated to cross reference powers

**Comment by broxen** [comment]
Updated to reflect in-progress status of PR #549 SuperGroups Implementation

**Comment by Magentah** [comment]
It seems like the City Info Kiosks and Stats are not part of Issue 0/1, and were added in Issue 2.

**Comment by broxen** [comment]
Yeah that's true, though we have the client-side logic to utilize those kiosks (they send `/kiosk home` to the server)

Definitely not a priority item, but at least something we can implement

**Comment by broxen** [comment]
Updated with some issues and fixed the completed list

**Comment by broxen** [comment]
Updated after latest merges. Will update again after Tailor PR merges.

**Comment by broxen** [comment]
Closing this and reopening after cleaning up a bit.

**Comment by broxen** [comment]
Please see #706
