### ISSUE TITLE
[Meta] Powers Roadmap

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#525]
## Summary
Now that #495 has been merged, I'm sure there will be interest in finishing the powers implementation. Here's a run-down on what the current road map for fully functioning Powers might look like. Suggestions very much welcome.

When tackling these, please create a new issue to track your progress, and cross-reference this Issue. Nem and I are available to answer any questions or to provide guidance on any particular issue.

Thank you!

### Simple Features To Implement
- [ ] Allow starting powers to be configured via settings.cfg
- [ ] Allow starting inspirations to be configured via settings.cfg
- [ ] Properly consider PowerType from m_power_tpl when using powers
- [ ] Properly consider Range from m_power_tpl when using powers
- [ ] Properly consider Accuracy from m_power_tpl when using powers
- [ ] Properly consider TargetTypes allowed from m_power_tpl when using powers
- [ ] Properly handle `$$` in commands sent to server (split to new command)

### Complex Features to Implement
- [ ] Power Animations (seqbits, and triggeredmoves)
- [ ] State Mode (needs research; this changes on power use)
- [ ] NetFx aka particles for powers!
- [ ] Active Powers Queue
- [ ] Recharge Timers
- [ ] Store Powers damage and other info not available in client files (maybe as json, or yaml?) on server
- [ ] Fully handle Leveling Up and awarding new powers/etc.
- [ ] Apply Inspiration Benefits when used (maybe using LUA?!?!)
- [ ] Apply Enhancement benefits to powers when used (maybe using LUA?!?!)
- [ ] Apply proper effect when Powers are used (maybe using LUA?!?!)

### Implemented Features
- [x] Grant Starting Powers
- [x] Grant Inherent Powers
- [x] Grant Temporary Powers at Creation (required by client)
- [x] Grant Starting Inspirations
- [x] Load/Save to Database, includes Powers Tray, Enhancements, Inspirations, Owned Powers
- [x] Handle Using/Moving/Trashing Inspirations, Enhancements, Powers
- [x] Handle Adding new Powers

## Related Issues and PRs
- [x] Merge #495 for preliminary powers support!
- [x] This issue should be added to #519 
- [ ] Add new issues as they relate

**Comment by eos428** [comment]
I am interested in doing some more of these. Can you open two issues for:
- Active Powers Queue and Recharge Timers
- Considering PowerType, Range, etc when using powers, should be condensable into 1 issue I believe

I'll probably work on these after my recent PRs are merged (EmailHandler aside). Just give me the details and pointers on what to do, and we'll do the rest together. Much appreciated!

**Comment by cyanpill** [comment]
**"Properly handle $$ in commands sent to server (split to new command)"**

Does this need any work? I can send in a command like **"/em dance$$say hello$$fly$$setlevel 20"** and it works the same way as if those commands were on separate lines.

**Comment by broxen** [comment]
oh, you're right! For some reason I though this wasn't implemented.

**Comment by cyanpill** [comment]
PR #598 has started the work on toggles and buffs, but more can be done. Applying the buffs to stats while they are on, and changing back when they are off, toggles actually toggling, and only recharging when turned off. And endurance cost for toggles, which will need a End recovery tick.

**Comment by broxen** [comment]
:+1: absolutely. Updated the issue body with both of our PRs and added the additional task items per your comment.

Thanks @cyanpill, you rock!

**Comment by broxen** [comment]
Powers array should actually be stored in Entity, and provided to Character as a pointer (because sendPowers() in character update).

Critters and NPCs may have powers too! Will update list

**Comment by broxen** [comment]
This will be replaced by #870
