### ISSUE TITLE
Correlate Map Indexes with Original Servers

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#584]
## Summary
There are couple of hints in the client code that indicate that original map numbers may not line up with what would be expected based upon level requirements or even map name. An example of this is the internal number of 29 for Galaxy City, which has a map name of City_01_03 and is one of the starting zones.

### Proposal
The community has data-mined nearly all the original map numbers while the game was still live. I propose we utilize those numbers in SEGS. The benefits of this may not be readily apparent, but it's early enough in our development that the change wont have any real impact.

The easiest place to find the original zone indexes is in the zone.cfg and travel.cfg files used with Paragon Chat. I've attached them here.

P.S. in the future we can create scripts to be read from, similar to these cfgs here.
[zone.cfg.txt](https://github.com/Segs/Segs/files/2402836/zone.cfg.txt)
[travel.cfg.txt](https://github.com/Segs/Segs/files/2402837/travel.cfg.txt)

### Tasks to Complete This Issue
- [ ] Re-index the maps in `map_definitions.cpp` to the official numbers pulled from zone.cfg (linked above) 
- [ ] Exclude, or comment out, maps that our client version doesn't have. The existing list in `map_definitions.cpp` should be definitive (missions maps aside)
- [ ] Test to verify we didn't bork something

**Example: **
```cpp
{3, "City_01_03", "maps/City_Zones/City_01_03/City_01_03.txt", "Galaxy City"},
// would become:
{29, "City_01_03", "maps/City_Zones/City_01_03/City_01_03.txt", "Galaxy City"},
```

### Bonus Tasks that would make you the most awesome-est person evah!
- Add spawn indicator name to the vector in `map_definitions.cpp` and leverage it for `/stuck` or zoning
- Move `g_defined_map_deltas` vector to some sort of flat file, either json, lua, (yaml?) or cfg, that we can read from on loading the server. This will make server-customization and (future) custom maps possible
- Utilize the attached `travel.cfg` to generate a list of zones for `/mapmenu`

**Comment by Cynicide** [comment]
Hey, I thought I'd have a go at this as I want to help, I'm pretty terrible with C\C++ but this struck me as a mostly data sanitation issue where I could probably help.

In map_definitions.cpp there is one zone I can't find anywhere in the provided cfg files or via googling. It's called "Enviro Nightmare". I've had a pretty good look but I can't seem to match it to anything. Anyone know if it's called something else in game?

**Comment by broxen** [comment]
It's either Eden or Creys Folly

**Comment by whitegryphon** [comment]
I believe that Eden was also called Woodvale and Crey's Folly was Venice in some of the documentation if that helps. Also, the Rikti Crash Site/War Zone was White Plains.

**Comment by Magentah** [comment]
Unless I remember wrong, Enviro Nightmare is a dev zone only and was never available to the public. I think there's a couple of zones that are like this

**Comment by broxen** [comment]
Can someone zone there and confirm?

**Comment by Magentah** [comment]
Looks like it. Loading there gives no load screen (just a random texture rather than a map name and map image), there's no name in the window title, there's no objects in the zone.

**Comment by broxen** [comment]
Awesome. Thanks for checking

**Comment by Cynicide** [comment]
I think I've got this working locally with the provided indexes. /mapmenu now uses the new indexes and it displays the correct names and teleports you to the correct zones. 

As far as the bonus tasks go:

Is the "spawn indicator name" just the SpawnLocation from the zone.cfg.txt? For example Eden would be "LinkFrom_City_04_01"

The second task talks about `g_defined_map_deltas` but I can't find this vector in the code, Is it a typo in the issue and it should be `g_defined_map_datas`? If I move this data out to a JSON file is there a place in the file hierarchy for it? I was thinking `Projects\CoX\Data`

Lastly, do you want me to open my own issue for these questions, or do I do that when I have a PR ready?

**Comment by Magentah** [comment]
You don't need to worry about the spawnLocation from the zone.cfg.txt as it looks like they just use a random possible spawn location. We read them from the scenegraph on load and store them separately as they're used for a number of things.

`g_map_defined_deltas` should be `g_map_defined_datas` yes. Having the file in `Projects\CoX\Data` seems fine to me.

You can raise a PR and just link to this issue. @broxen can assign this to you as you're working on it. Ask any questions in here or discord.

**Comment by Cynicide** [comment]
OK, Do I need any special permissions? I tried to push a branch to create a PR and I got a permission error.

**Comment by Magentah** [comment]
You should fork Segs to your own repository, then push it to that. You can then PR from your repository to the main Segs repository
