### ISSUE TITLE
[Meta] Required Tasks before v0.6.0 Release

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#655]
## Summary
This issue will track any administrative tasks necessary prior to release of v6. Feel free to discuss or add additional tasks in the comments below.

I'm assigning all stakeholders to this issue for tracking. Feel free to unassign yourselves as necessary.

- [x] Close out, or move any and all remaining tasks from v6 Milestone (this should be the only task remaining)
- [x] Move any closed v7 items to v6 milestone (since they were completed in time)
- [x] Update any client versions in SEGSAdmin for version check
- [x] Update `motd.smlx` in project to reflect changes and new version number
- [x] Update `Version.h` in project
- [x] Update `AUTHORS.md` in project
- [x] Update any mentions of client version in READMEs or wiki docs.
- [x] Build Release candidate for target platforms (currently Windows only)
- [x] Run final "clean room" install and full scope test of new release candidate (Can I make a new Character and run around using a fresh install on a new database?)
- [x] Remove unit tests, test client, and unused runtimes from release output directory
- [x] Include OpenSSL DLLs (and adhere to any licensing requirements) in Windows release zip archive
- [x] Upload release to GitHub
- [x] Post announcements to social media and sticky post on forums
- [x] Have a cookie 🍪

**Comment by ldilley** [comment]
Thank you for compiling the requirements and creating this comprehensive meta issue to track things, @broxen. Well done, sir. I've added a task to include the OpenSSL DLLs in the release to appease @JamesDW1. :)

**Comment by broxen** [comment]
Weeeeeee!
