### ISSUE TITLE
[Meta] Complete SEGSLauncher (and Verifier)

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#676]
_As a result of the discussion in https://github.com/Segs/Segs/issues/449#issuecomment-397895198_

## Summary
This meta issue is aimed at coordinating the effort to complete SEGSLauncher (formerly SLAV) utility for us with the server.

### Initial Tasks to Complete
- [ ] Rename SLAV utility to SEGSLauncher
- [ ] Rework to follow design principles of SEGSAdmin (visual parity helps users feel comfortable)
- [ ] Accept a list of public servers to allow users to select a server to join
- [ ] Also allow a custom IP to be entered
- [ ] Verify the client version is correct
- [ ] Verify that all client files are present

Feel free to add any additional tasks or considerations here, and discuss below.

**Comment by broxen** [comment]
@miles200 I'm assigning you to lead this effort, per our conversation in Discord.

That said, anyone is free to tackle these tasks. Please just reply here with your intent.

**Comment by miles200** [comment]
@broxen This is still on my list, when are we looking for 0.7 release? I should have something by then!

**Comment by broxen** [comment]
Spring 2019. We'll firm up a date as we work our way through various PRs and get through the holiday season

**Comment by broxen** [comment]
An RPC call is likely more bulletproof. As we've seen the server can "silent crash" where just the dbserver has dropped. Maybe checking all IPs and open ports? Of course, the DBServer may block outside traffic... Seems RPC is the best way, let the server tell us it's online.

**Comment by miles200** [comment]
Just found this from something @whitegryphon did .. looks perfect for what I need
```
QString AdminRPC::ping()
{
    QString response = "pong";
    return response;
}

QString AdminRPC::getStartTime()
{
    return m_start_time;
}```

**Comment by broxen** [comment]
That's perfect

**Comment by dracc** [comment]
Looks like a valid idea, however default RPC behavior is because of security reasons still to only listen on 127.0.0.1 as far as I understand. It would require changes in server code to implement this.

**Comment by ldilley** [comment]
Binding to the local loopback interface is indeed the default. However, @whitegryphon implemented a `ReadConfig()` method that is called from the `AdminRPC` constructor. If you add a section for `[AdminRPC]` in `settings.cfg` and make it contain `location_addr` pointing to another address, you should be good to go.

**Comment by miles200** [comment]
@broxen Do we need to verify client files every launch, or just once as part of initial setup, then set a flag to tell the launcher this has been done.

**Comment by broxen** [comment]
I would verify at setup. Files shouldn't change and if we need to check them again we can do it when we update the launcher

**Comment by miles200** [comment]
Hi @broxen 

Edited the description to propose feature list for 0.7. Will have some time this weekend to finish up hopefully. Thoughts?

**Comment by broxen** [comment]
Sounds perfect. Thanks Miles!

**Comment by miles200** [comment]
Note to self: Have edited jcon-cpp RPC timeout value from 60000 to 20000
