### ISSUE TITLE
[Meta] How Can I Help? aka Future Server Features, and Roadmap to v0.7

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#706]
## Summary
We need to implement these items one by one. I'm marking this `good-first-issue` as although these aren't all simple tasks, this can become a great resource for new members of all skill levels looking for how to help in meaningful ways.

**This also provides a _loose_ Roadmap for v0.7, but note that some features may be pushed back depending upon time and level of completion.**

When you take on one of the tasks (or groups) below, please [create a new issue](https://github.com/Segs/Segs/issues/new) to track your progress. Thank you!

> See FloatingDamage for reference on how to implement server->client pkt communication: [Segs/Projects/CoX/Servers/MapServer/Events/FloatingDamage.h](https://github.com/Segs/Segs/blob/develop/Projects/CoX/Common/Messages/Map/FloatingDamage.h)

## Check the Issue Queue
- [Issues labeled `bug`](https://github.com/Segs/Segs/labels/bug)
- [Issues labeled `good first issue`](https://github.com/Segs/Segs/labels/good%20first%20issue)
- [Issues labeled `enhancement`](https://github.com/Segs/Segs/labels/enhancement)
- [Issues labeled `wishlist`](https://github.com/Segs/Segs/labels/wishlist)

### Low Difficulty
- [ ] Force Client Logout (boot client) (packet 12) -- In progress #700 
- [ ] Client Console Output (packet 17)
- [ ] Client Console PrintF (packet 19)
- [ ] Send VisitLocations (not sure of purpose, maybe early badges?) (pkt 63)
- [ ] Correlate Map Indexes with Original Servers -- In Review: see #584
- [ ] Update "Current Features" list on Wiki -- see #554
- [ ] Replace `std::unique_ptr<T>(newT())` with `std::make_unique()` calls -- see #532 
- [ ] Normalize basic type arguments -- see #357 
- [ ] Update server architecture on wiki -- see #333 
- [ ] Update doxygen comments throughout the code base -- see #360 #699 
- [ ] Implement `getEntitiesInRadius()` and `getEntitiesInCone()` helper methods -- see #686 

#### Misc: 
- [ ] Map Cells Fog of War (packet 22) - Partially implemented #371 
- [ ] Control Player (pkt 38)
- [ ] Bug Report (pkt 80) -- Track in: #287 #35 
- [ ] Initiate Respec - using `/start_menu 13` somehow? Otherwise spoof with slash command and training?
- [ ] Implement City Info Kiosk and Stats -- This is partially done (see: StandardDialogCmd, and implement `/kiosk home`). Will need to track Victors, Punishers, Healers, and Nemeses on a daily and monthly basis.
- [ ] Database schema migrations for updates to the database (aka dbtool v5)
- [ ] *Send Team-removal and Sidekick-removal messages, aka TeamService -- see #555 and #642* 
- [ ] Implement proper door transfers by linking doors to `GoToSpawn` nodes
- [ ] Extend RPC hooks to allow additional information to be shared with Web-UI, such as Number of Clients connected, Total number of Clients Registered, and more. -- see #633 
- [ ] Extend StateBelief and Stagger Entity updates to improve performance -- see #690
- [ ] Character Constructor fires 10+ times per Entity -- see #689 

#### Roadmaps
- [ ] Finalize Powers Roadmap - see #525  
- [ ] Compelete SEGSLauncher and Verifier - see #676 
- [ ] Finish Email Handler -- see #618 

#### Stores
Other packets TBD
- [ ] Store Open (pkt 78)
- [ ] Store Close (pkt 79)

#### Taskforces
May require some additional Taskforce logic
- [ ] Taskforce Kick (packet 26)
- [ ] Taskforce Quit (packet 27)

#### Mission Related
Too fully implement will require mission maps
- [ ] Mission Entry Text (pkt 49)
- [ ] Mission Kick (pkt 50)
- [ ] Mission Objective Timer (pkt 73)

#### *Implement Supergroup Registration -- In Progress: #549*
- [x] Supergroup Offer (pkt 29)
- [x] Supergroup Create (pkt 30)
- [x] Supergroup Costume (pkt 31)
- [x] Register Supergroup (pkt 74)
- [ ] Supergroup Handler/Service

### High Difficulty
- [ ] Proper per-map NPC Serialization #73 - Right now Outbreak spawns correctly, but AP, KR, etc do not. 
- [ ] Encounter Spawns
- [ ] Animations (aka Sequences)
- [ ] Particles and FX (aka NetFX)
- [ ] Fix Entity Movement #94
- [ ] Collision #81 
- [ ] Implement Mission Maps
- [ ] Mapviewer Improvements
- [ ] Client Patch Improvements
- [ ] StatisticsService - Track all the things!

**Comment by broxen** [comment]
Please reach out with any questions about specific tasks
