### ISSUE TITLE
[Meta] Issue 23+ Client Support

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#72]
## Update as of August 2018
Current consensus is that developing a custom client may actually prove to be faster, and a better use of resources than reverse-engineering the I23+ client. Preliminary work has begun on AuthExerciser (#237), MapViewer (#238), and Client Gfx Patch (#450) which lay a foundation for a custom client. Additional work on a QT based GUI resources should be followed here: Segs/Segs-Data#6

**The below is left here for posterity, and to provide a sort of loose roadmap for feature parity.**

## Summary
This is a meta issue, for proposed Issue 23+ Client support. As the term "issue" is vague and may refer to either a GitHub issue, or a City of Heroes Client Release Milestone, I'll standardize the usage here by referencing all CoX Client release milestones as such: `I##` or `I24` or `I7` or by referring to them as `client patches`

**The Goal** here is to provide information and resources should a desire rise to support later clients, or should a developer come to the table interested in forking current development to a later client patch, such as I23+

This meta issue should identify and reference other issues or concerns that may prevent, or create hurdles for development towards I23+ support. Additionally, this should support general discussion revolving around late-game client support viability.

When submitting new issues related to this meta, please tag with the (proposed) `Issue23` label for sorting.

### **Known release-blocker Issues:**
- [ ] _issues to go here_

### **Issues needing more research:**
- [ ] Blowfish encryption likely changed every time the client was patched, which means that packet calls would have to be rewritten to work with the new client.
- [ ] Is there a way to configure the server for a specific CoX patch period? Something like `server-issue: 11`
- [ ] The server should check client version and output a message for versions incompatible with the server issue
- [ ] Should the scripting system be able to target a specific release version?
- [ ] Target: CoH release (I0)
- [ ] Target: CoV release (I6)
- [ ] Target: Going Rogue release (I18)
- [ ] Target: Sunset Client (I24beta)

### **Additional Game Subsystems that will need development**
- [x] Tailor System (this may be handled mostly client side)
- [ ] Exemplaring & Sidekicking
- [ ] Respec'ing
- [ ] Personal Badges, Exploration Badges, Accolades, and Supergroup Badges
- [ ] PvP
- [ ] City Info Terminals & Server/Player Stats
- [ ] Enhancement Diversification
- [ ] Arenas and Arena Combat
- [ ] Villian Hero Type, Classes, and Powersets
- [ ] Mission Architect
- [ ] Wentworth's Auction House
- [ ] SuperGroup Bases
- [ ] Rogue/Vigilante Hero Types
- [ ] Holiday Events (Halloween, Winter, etc.)
- [ ] Ski Chalet ski challenge
- [ ] Ouroboros ([Flashback System](https://paragonwiki.com/wiki/Flashback)) 
- [ ] Salvage and Invention System
- [ ] Incarnate System
- [ ] Day Jobs

**Comment by broxen** [comment]
Closing this, as SEGS Engine will support I24 assets at runtime!
