### ISSUE TITLE
[Meta] Required Tasks before v0.7.0 Release

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#807]
## Summary
This issue will track any administrative tasks necessary prior to release of v0.7. Feel free to discuss or add additional tasks in the comments below.

I'm assigning all stakeholders to this issue for tracking. Feel free to unassign yourselves as necessary.

- [x] Close out, or move any and all remaining tasks from v0.7 Milestone (this should be the only task remaining)
- [x] Move any closed v0.8 items to v0.7 milestone (since they were completed in time)
- [x] Create label for sorting `v0.7.0` Release Issues
- [x] Close #706 and open a new Roadmap for v0.8
- [x] Update any server versions in SEGSAdmin for version check
- [x] Update `motd.smlx` in project to reflect changes and new version number
- [x] Update `Version.h` in project
- [x] Update `CMakeList.txt` in root with Version Changes
- [x] Update `AUTHORS.md` in project
- [x] Update any mentions of server version in READMEs or wiki docs.
- [x] Build Release candidate for target platforms (currently Windows only)
- [x] Run final "clean room" install and full scope test of new release candidate (Can I make a new Character and run around using a fresh install on a new database?)
- [x] Remove unit tests, test client, and unused runtimes from release output directory
- [x] Include OpenSSL DLLs (and adhere to any licensing requirements) in Windows release zip archive
- [x] Upload release to GitHub
- [x] Post announcements to social media and sticky post on forums
- [x] Have a cookie 🍪
