### ISSUE TITLE
[Meta] Custom Client Roadmap

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#923]
Per the discussion in [Discord](https://discord.segs.dev) about creating a new custom client to work with the new Godot based SEGSEngine.

We'll need both programmers and artists to create fallback assets, so I've broken the road map into two parallel paths below.

### Development https://github.com/Segs/Segs-Client:
_See SEGS Launcher Roadmap here: https://github.com/Segs/Segs/issues/676_
- [x] Build basic client with no functionality https://streamable.com/pxx4j
- [ ] Build basic client with UI for login (later, login to be moved to SEGS Launcher)
- [ ] Build client to connect to AuthServer
- [ ] Build client to connect to GameServer
- [ ] Build client basic UI, loading UI assets from piggs (or derivatives)
- [ ] Build client that loads sounds and music
- [ ] Build client that loads maps from piggs
- [ ] Build client that loads basic models and textures from piggs
- [ ] Build client that loads animations and FX

### Media Assets https://github.com/Segs/Segs-Assets:
_See SEGS Launcher Concept Discussion Here: https://github.com/Segs/Segs-Client/issues/4_
- [ ] New Client Logo, or Use Existing Logo? [Current Logo Here](https://github.com/Segs/Segs-Client/blob/master/SEGSLauncher/Resources/Icons/app-icon.svg)
- [ ] New Background Art for SEGS Launcher [Current Hero Shot](https://github.com/Segs/Segs-Client/blob/master/SEGSLauncher/Resources/Images/bluestreak.png)
- [ ] New fallback UI Layouts for Log In / Server Selection
- [ ] New fallback UI Layouts for Character Creation Screen
- [ ] New fallback UI Layouts for Character Select Screen
- [ ] New fallback UI Layouts for Gameplay Screen
- [ ] New fallback UI Layouts for SuperGroups Screens
- [ ] New fallback Sounds
- [ ] New fallback Music
- [ ] New fallback Models
- [ ] New fallback Animations
- [ ] New fallback Textures

Feel free to comment below with additions, changes, proposals, etc.

**Comment by broxen** [comment]
Assigning stakeholders. Feel free to remove yourself after reviewing.

**Comment by jgwinner** [comment]
Can the art be the same basic model, but upscaled / uprezed? Would that violate a "visual copyright" if all the bits are different?

        == John ==

**Comment by broxen** [comment]
This is still a valid roadmap for the Segs/SegsEngine client based on Godot, so I'm bumping this for the 👀
