### ISSUE TITLE
[Meta] Power Builder Tool

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#973]
As part of the SEGS toolkit, we need a tool to build powers, inspirations, enhancements, etc. This tool should take input on the characteristics of powers and generate a `powers.json` which can be loaded by the server. This will allow server admins to modify base powers, create new powers, powersets, inspirations, enhancements, and anything else adjacent to the "item" system.

The power builder will take templated SVG files of UI elements, and based upon configured settings for each power, generate the necessary Icon for use in the client. An example of the output json may look like:
```json
{
    name: "Repulsing Torrent",
    category: "Kinetic",
    color: #0F5242,
    icon: knockback,
    icon_color: #395A9E,
    target_type: cone,
    // power stats and so on
}
```
which would generate the appropriate icon (cone border, correct colors, correct icon, etc):
![KineticAttack_RepulsingTorrent](https://user-images.githubusercontent.com/10159505/198720403-5d0bb21c-81a0-4249-a2ab-558db4cbc5a5.png)

`binTool` already parses powers.bin and exports powers.json, so we can reuse the code there.

We'll need both programmers and artists to create fallback assets, so I've broken the road map into two parallel paths below.

### Development:
- [ ] Build basic Power Builder tool and add it to the project cmake
- [ ] Load from Bin files
- [ ] Load from XLS for custom data (load up your custom powersets quickly)
- [ ] Load Powers
- [ ] Load Enhancements
- [ ] Load Inspirations
- [ ] Display Tree of Powersets and Powers with attributes in editable side-pane window, provide dropdowns for common values `target_type` etc.
- [ ] Render configured Icon (based upon power attributes such as `target_type` and defined `bg_color`)
- [ ] Render configured FX (with defined colors, and timing)
- [ ] Render configured Animations (this and FX can be similar to the custom colors configurator for Powers in CoH)
- [ ] Export as `powers.json` to be loaded by server for use at runtime

### Media Assets https://github.com/Segs/Segs-Assets:
- [ ] New fallback icons and symbols for use on different Powers or Inspiration icons etc (SVG format)
- [ ] New fallback SVG templates for Final UI icon generation (SVG format... sample attached below)
- [ ] New fallback Sound FX
- [ ] New fallback Animations
- [ ] New fallback FX

### Future (post v1.0) Release
- [ ] Expand to allow for building custom Archetypes!
- [ ] Expand to allow for building custom Origins!
- [ ] Expand to allow for building custom Badges!
- [ ] Expand to allow for building custom Salvage!
- [ ] Expand to allow for building custom Invention Recipes!

Tagging known stakeholders. Feel free to comment below with additions, changes, proposals, etc.

### Screenshot and SVG Template Example
![Screenshot_from_2022-10-28_09-21-32](https://user-images.githubusercontent.com/10159505/198718571-c46398bb-f928-43b1-90c7-0ba0988f1465.png)
#### SVG Example Template
![inspiration_template](https://user-images.githubusercontent.com/10159505/198718573-7fdcd356-d1ee-4667-bfdc-653d912a2b30.svg)
